project:
  type: website
  output-dir: _site

website:
  title: "rogerkrw.com.br"
  site-url: https://rogerkrw.com.br
  description: Rogério Kreidlow's website
  navbar:
    right:
      - blog.qmd
      - text: "Bio"
        file: about.qmd
      - portfolio.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/rogerkrw/
  google-analytics: "G-GV591LTXJB"
  back-to-top-navigation: true
  page-footer: "© Copyright 2023, Rogério Kreidlow. Feito com [Quarto](https://quarto.org/)."

format:
  html:
    fontsize: 1em
    theme:      
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    include-in-header: |
      <script type="text/javascript">
          (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "scz2yji5c8");
      </script>

execute:
  cache: true

resources:
  - CNAME