project:
  type: website
  output-dir: docs

website:
  title: "Rogério Kreidlow"
  site-url: "https://rogerkrw.github.io"
  description: "Site pessoal"
  favicon: logo.ico
  google-analytics: "G-SKSQF6JWNM"
  search:
    location: navbar
    type: overlay
    keyboard-shortcut: ["F2"]    
  navbar:    
    logo: logo.png
    logo-alt: "Foto de Rogério Kreidlow"
    logo-href: index.qmd
    background: primary
    page-layout: full    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/rogerkrw       
      - icon: github
        href: https://github.com/rogerkrw        
  page-footer: "Copyright © 2025 Rogerio Kreidlow"
format:
  html:
    css: styles.scss
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    grid:
      body-width: 700px
    include-in-header: clarity-script.html
toc: true


