project:
  type: website
  output-dir: docs
  

website:
  title: "rogerkrw.com.br"
  google-analytics: "G-H1VN6PCJ26"
  navbar:
    right:
      - portfolio.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/rogerkrw/

format:
  html:
    theme: cosmo
    css: styles.css